### PR TITLE
Oor notation change

### PR DESCRIPTION
**Pull request by Albacusphetical**
I feel there are issues with how readable oor notes are, after sightreading lots of music with the current notation I've found myself with these scenarios:

1.  When a chord has more than one oor note, it is sometimes hard to spot quickly where the oor notes ends.

2. Having oor notes positioned on the wrong side can make it sound off, this can be fine in some places but where theres music that uses oor notes in the lower and higher octaves, unlike with shifts, it affects the sound alot because the distance between the oor octaves is much greater.

3. \***Despite the notes being underlined, related to scenario 1, it can still see be a bit tricky to quickly see if it is actually a oor note and not a in-range note because they share the same characters.**

This PR trys to address these scenarios like this:

1. Add a seperator between oors and in range notes, i chose a single quote mark since it doesn't take up much space. You can find it in the following formats in chords if oors are inorder for example(see below): [oors'in-range'oors] or [oors''oors]. 
For single oor notes theres only 1 single quotation mark on either side depending on whether it is low octave or high octave. 
High octave: 'oor 
Low octave: oor'

2.  An option to position the oor notes inorder i.e. on either side

3. **Unicode characters that look like the character that needs to be played, this can be seen in text too. 
\*Side note: I am not so sure about this since we have a seperator now, it may not be necessary, it could be done only for images and the copy text button could give it fully in ascii for example. I'm aware that pasting these characters into games like Roblox is problematic. If we decide to do it only for images, could as well just style the original ascii characters than use unicode. Theres many options, lemme know what you think.**

### Beyond readability too, maybe?
Giving a fixed notation for oor seperators could help those who want to be able to use oor notes from a sheet with auto across different VP apps in the future.

### CODE REVIEW

**Comment by ArijanJ** [comment]
OORs being in order is a really nice addition.

The new separator probably shouldn't be rendered if there are no notes on that side because ['etup'H] is less readable than [etup'H], but this could cause ambiguity (is 'H a high note or are etup' all low notes?) so I'm not sure how we could pursue this.

Point#3 won't be an issue with this separator, so I think we can keep underline for images.

Alternatively we could also just remove the whole underline/`border-bottom` cause it's really cluttered right now, with both the unicode and the underline.
The best option for this would probably be to give users a choice on how to render OORs [either underline or unicode, and force unicode if they click on "copy text"].

Thoughts?

**Comment by Albacusphetical** [comment]
The first issue you pointed out is exactly why in-range notes are wrapped, having the separator on either side. Before this PR, I did try the "[etup'H]" option if the oors position was Start/End but I found out it was ambiguous like you said if theres more oor notes than in-range notes for example then its an issue. It's probably for the best to have them at both sides so it's consistent across sheets.

About the other points you mentioned, I have played around with different options, I think unicode or maybe uppercase ascii with separator without underline seems the clearest. 

However, I found with uppercase ascii its a bit harder to read single oor notes but you get the same benefits regardless from the separator in chords containing oors, ascii can be pasted anywhere too, which would be compatible with Roblox for example. We could figure out a clearer notation for a single oor note if we go this route to make it usable everywhere? or we could make a sacrifice here and choose unicode 🤔? The unicode characters currently are easier to catch as an oor in your peripheral vision but unfortunately they can't be used everywhere 🤷

When it comes to options, ideally, especially in copied text, I think there should be only one notation for oors that can both carry over to text and image otherwise it will get confusing if sheets aren't consistent. It might not be any harm though if the oor notes had an option to be underlined/styled anyway in images if we gave users an option to choose if they want them to be. That would be fine as long as you can clearly see whats oor or in-range like with using separators as in text.

Lemme know what you think.

note: I have added a fix for when chords have only oors on either side: [oors''] or [''oors]

**Comment by ArijanJ** [comment]
I don't know whether Unicode is the way to go, it's not very portable as you already said (example: vscode renders "𝗶" as usual, but my browser just doesn't):
image


The separator idea is nice, although I haven't seen many chords with more than 1 oor, but maybe we could adapt it to something like `['et|etup|'j]`?
This is even more visible, and in this case the `'` will only have one meaning (press with ctrl, rather than seeing it in a chord and it having minimal impact). Some more examples:
`['0|8wu]`
`[pj|'d]`
`[c|'pd]`
Maybe we could even change it to something more drastic like a `:` or even a `+`:
`[wo|+s]`
`[+4q|1h]`
`[epm|+oj]`

_Also, this probably should've been an issue first until we figure out the optimal way to implement this :(_

**Comment by Albacusphetical** [comment]
I think if we had the separator like |, it could be confused with a uppercase i, it also makes it feel more intimidating to play. I think if we used this ":" then it would look more clear for single notes and chords like this:

oor: OR :oor
[oors:in-range:oors]
etc.

I think that's clearer in text than what I suggested last time. 

About reducing separators, I like that idea, what if lower/starting oors was minus and upper/ending oors was +, for example:

[-oors:in-range] or [in-range:+oors]
[-oors:in-range:+oors]
[-oors+oors]

(these would be - or + according to the actual note instead of position)
[-oors]
[+oors]
-oor or +oor 

So separators would only be used if there is a mix of oors and in-range notes.

Lemme know what you think of that.

**Comment by ArijanJ** [comment]
If we switch away from unicode, [ab:cdef:gh] won't be very clear because your eyes are going to see them as regular notes before reaching the `:`, [-ab:cdef:+gh] does solve this but it's too cluttered I think.

Maybe we combine these and do something like:
[:8'wuo]
[psj:f]
[:t'etup:j]
The `'` is only useful for low -> regular notes, since there's nothing after the high ones.

`:` always means ctrl again, regular notes are regular notes, and `'` is just a visual aid. (pretty much my previous idea with one less separator and `'` instead of `|`)
Worth noting that the majority of good sheets won't have oors on both sides in the same chord, so the inconsistency probably won't matter much. I think I like this best out of everything so far for ASCII-only representation.

**Comment by Albacusphetical** [comment]
That's a good choice, less clutter and good clarity, so would the rules be like this?

[:oors'in-range:oors]
[:oors'in-range]
[in-range:oors]
[:oors]
:oor

Also it's true that a good number of sheets won't have oors on both sides unless you're playing crazy stuff :D, as long as it's clear and doesn't come as a surprise thats what matters.

**Comment by ArijanJ** [comment]
Yeah, I think that's pretty good, we can work on implementing it if you feel that it works.

**Comment by Albacusphetical** [comment]
I am happy with that, I can create an update for this soon

**Comment by Albacusphetical** [comment]
Updated, lemme know how that is

**Comment by ArijanJ** [comment]
Yep, great! Would it be possible to bring back the underline or is everything different now?

Since this replaces the oor prefix, you can just get rid of that their entire thing and we could merge this.

**Comment by Albacusphetical** [comment]
It is easy to add back, I only removed border-bottom from the span, I think we could add style options to bold/underline oors. Removing oor prefixes could be done with your permission. What do you think?

**Comment by ArijanJ** [comment]
Actually, we could maybe let users chose which one to use (like the oor prefix is right now), but keep `:` as the default.

Feel free to finish up with whatever else you think should be done and let me know when this is ready to merge :)

**Comment by Albacusphetical** [comment]
Done, oors are now bolded, and you can't set it to certain characters like any characters used for existing vp notation, only ascii allowed, and some invisible characters are not allowed

**Pull request merged**
